// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using summer_training_app.Data;

#nullable disable

namespace summer_training_app.Migrations
{
    [DbContext(typeof(SummerTrainingDBContext))]
    [Migration("20260813195307_EnumsToStringConversion")]
    partial class EnumsToStringConversion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("summer_training_app.Entities.Core.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CollegeName")
                        .IsUnique();

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.CollegeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("CollegeId", "Title")
                        .IsUnique();

                    b.ToTable("CollegeDocuments");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.CollegeRepresentative", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("CollegeId");

                    b.HasIndex("UserId", "CollegeId")
                        .IsUnique();

                    b.ToTable("CollegeRepresentatives");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.CompanyRepresentative", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("CompanyRepresentatives");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Student"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "CompanyRep"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "CollegeRep"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            Id = 5,
                            RoleName = "BasicUser"
                        });
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.RoleUpgradeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("OfficialEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProofFilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("RequestedRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("CollegeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RequestedRoleId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RequestedRoleId")
                        .IsUnique()
                        .HasFilter("[Status] = 'Pending'");

                    b.ToTable("RoleUpgradeRequests");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.StudentProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GPA")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("Major")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniversityIdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("CollegeId");

                    b.HasIndex("UniversityIdNumber")
                        .IsUnique()
                        .HasFilter("[UniversityIdNumber] IS NOT NULL");

                    b.ToTable("StudentProfiles", t =>
                        {
                            t.HasCheckConstraint("CHK_GPA_Range", "GPA >= 0 AND GPA <= 5");
                        });
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.TrainingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.ToTable("TrainingRecords", t =>
                        {
                            t.HasCheckConstraint("CHK_Dates_Logic", "EndDate > StartDate");
                        });
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.TrainingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AcceptanceLetterPath")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedCompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "AcademicYear", "Semester", "CompanyId")
                        .IsUnique()
                        .HasFilter("[CompanyId] IS NOT NULL");

                    b.ToTable("TrainingRequests", t =>
                        {
                            t.HasCheckConstraint("CHK_Dates_Logic", "StartDate > GETUTCDATE()")
                                .HasName("CHK_Dates_Logic1");
                        });
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentReportId");

                    b.HasIndex("StudentReportId", "QuestionId")
                        .IsUnique();

                    b.ToTable("ReportAnswers");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollegeSupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanySupervisorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StudentReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeSupervisorId");

                    b.HasIndex("CompanySupervisorId");

                    b.HasIndex("StudentReportId");

                    b.HasIndex("StudentReportId", "Phase")
                        .IsUnique();

                    b.ToTable("ReportEvaluations", t =>
                        {
                            t.HasCheckConstraint("CK_ReportEvaluation_PhaseOwner", "(Phase = 'CompanyEvaluation' AND CompanySupervisorId IS NOT NULL AND CollegeSupervisorId IS NULL) OR (Phase = 'CollegeEvaluation' AND CollegeSupervisorId IS NOT NULL AND CompanySupervisorId IS NULL)");
                        });
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OptionsPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("OrderPosition")
                        .HasColumnType("tinyint");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("ReportQuestions");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(day, 7, GETUTCDATE())");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("RequiresCollegeEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("RequiresCompanyEvaluation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("CollegeId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ReportTemplates", t =>
                        {
                            t.HasCheckConstraint("CK_ReportTemplate_Owner", "(CollegeId IS NOT NULL AND CompanyId IS NULL) OR (CollegeId IS NULL AND CompanyId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.StudentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TrainingRecordId");

                    b.ToTable("StudentReports");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.CollegeDocument", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.College", "College")
                        .WithMany("Documents")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.CollegeRepresentative", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.College", "College")
                        .WithMany("CollegeRepresentatives")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Entities.Core.User", "User")
                        .WithOne("CollegeRepresentative")
                        .HasForeignKey("summer_training_app.Entities.Core.CollegeRepresentative", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("User");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.Company", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("summer_training_app.Entities.Core.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.CompanyRepresentative", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.Company", "Company")
                        .WithMany("CompanyRepresentatives")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Entities.Core.User", "User")
                        .WithOne("CompanyRepresentative")
                        .HasForeignKey("summer_training_app.Entities.Core.CompanyRepresentative", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.RoleUpgradeRequest", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.College", "College")
                        .WithMany("RoleUpgradeRequests")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Entities.Core.Company", "Company")
                        .WithMany("RoleUpgradeRequests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Entities.Core.Role", "RequestedRole")
                        .WithMany("RoleUpgradeRequests")
                        .HasForeignKey("RequestedRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Entities.Core.User", "ReviewedBy")
                        .WithMany("ReviewedRoleUpgradeRequests")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Entities.Core.User", "User")
                        .WithMany("RoleUpgradeRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Company");

                    b.Navigation("RequestedRole");

                    b.Navigation("ReviewedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.StudentProfile", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.College", "College")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Entities.Core.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("summer_training_app.Entities.Core.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("User");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.TrainingRecord", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.Company", "Company")
                        .WithMany("TrainingRecords")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Entities.Core.StudentProfile", "Student")
                        .WithMany("TrainingRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.TrainingRequest", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.Company", "Company")
                        .WithMany("TrainingRequests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Entities.Core.CollegeRepresentative", "ReviewedBy")
                        .WithMany("ReviewedTrainingRequests")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Entities.Core.StudentProfile", "Student")
                        .WithMany("TrainingRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ReviewedBy");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.User", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportAnswer", b =>
                {
                    b.HasOne("summer_training_app.Entities.Reports.ReportQuestion", "ReportQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Entities.Reports.StudentReport", "StudentReport")
                        .WithMany("Answers")
                        .HasForeignKey("StudentReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportQuestion");

                    b.Navigation("StudentReport");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportEvaluation", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.CollegeRepresentative", "CollegeSupervisor")
                        .WithMany("Evaluations")
                        .HasForeignKey("CollegeSupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Entities.Core.CompanyRepresentative", "CompanySupervisor")
                        .WithMany("Evaluations")
                        .HasForeignKey("CompanySupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Entities.Reports.StudentReport", "StudentReport")
                        .WithMany("Evaluations")
                        .HasForeignKey("StudentReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollegeSupervisor");

                    b.Navigation("CompanySupervisor");

                    b.Navigation("StudentReport");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportQuestion", b =>
                {
                    b.HasOne("summer_training_app.Entities.Reports.ReportTemplate", "ReportTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportTemplate");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportTemplate", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.College", "College")
                        .WithMany("ReportTemplates")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Entities.Core.Company", "Company")
                        .WithMany("ReportTemplates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Entities.Core.User", "CreatedByUser")
                        .WithMany("CreatedReportTemplates")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.StudentReport", b =>
                {
                    b.HasOne("summer_training_app.Entities.Core.StudentProfile", "StudentProfile")
                        .WithMany("StudentReports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Entities.Reports.ReportTemplate", "ReportTemplate")
                        .WithMany("StudentReports")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Entities.Core.TrainingRecord", "TrainingRecord")
                        .WithMany("StudentReports")
                        .HasForeignKey("TrainingRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportTemplate");

                    b.Navigation("StudentProfile");

                    b.Navigation("TrainingRecord");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.College", b =>
                {
                    b.Navigation("CollegeRepresentatives");

                    b.Navigation("Documents");

                    b.Navigation("ReportTemplates");

                    b.Navigation("RoleUpgradeRequests");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.CollegeRepresentative", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("ReviewedTrainingRequests");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.Company", b =>
                {
                    b.Navigation("CompanyRepresentatives");

                    b.Navigation("ReportTemplates");

                    b.Navigation("RoleUpgradeRequests");

                    b.Navigation("TrainingRecords");

                    b.Navigation("TrainingRequests");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.CompanyRepresentative", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.Role", b =>
                {
                    b.Navigation("RoleUpgradeRequests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.StudentProfile", b =>
                {
                    b.Navigation("StudentReports");

                    b.Navigation("TrainingRecords");

                    b.Navigation("TrainingRequests");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.TrainingRecord", b =>
                {
                    b.Navigation("StudentReports");
                });

            modelBuilder.Entity("summer_training_app.Entities.Core.User", b =>
                {
                    b.Navigation("CollegeRepresentative")
                        .IsRequired();

                    b.Navigation("CompanyRepresentative")
                        .IsRequired();

                    b.Navigation("CreatedReportTemplates");

                    b.Navigation("ReviewedRoleUpgradeRequests");

                    b.Navigation("RoleUpgradeRequests");

                    b.Navigation("StudentProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.ReportTemplate", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("StudentReports");
                });

            modelBuilder.Entity("summer_training_app.Entities.Reports.StudentReport", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
