// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using summer_training_app.Data;

#nullable disable

namespace summer_training_app.Migrations
{
    [DbContext(typeof(SummerTrainingDBContext))]
    [Migration("20260805121023_updateData")]
    partial class updateData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("summer_training_app.Models.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeName = "كلية علوم الحاسب",
                            CreatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6031)
                        });
                });

            modelBuilder.Entity("summer_training_app.Models.CollegeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.ToTable("CollegeDocuments");
                });

            modelBuilder.Entity("summer_training_app.Models.CollegeRepresentative", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("CollegeId");

                    b.ToTable("CollegeRepresentatives");
                });

            modelBuilder.Entity("summer_training_app.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "شركة السقيفة لتطوير الأعمال",
                            CreatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6115),
                            IsApproved = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("summer_training_app.Models.CompanyRepresentative", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyRepresentatives");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentReportId");

                    b.ToTable("ReportAnswers");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanySupervisorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StudentReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanySupervisorId");

                    b.HasIndex("StudentReportId");

                    b.ToTable("ReportEvaluations");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionsPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("ReportQuestions");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("ReportTemplates");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.StudentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TrainingRecordId");

                    b.ToTable("StudentReports");
                });

            modelBuilder.Entity("summer_training_app.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Student"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "CompanyRep"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "CollegeRep"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("summer_training_app.Models.RoleUpgradeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfficialEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProofFilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RequestedRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("RequestedRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleUpgradeRequests");
                });

            modelBuilder.Entity("summer_training_app.Models.StudentProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GPA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Major")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniversityIdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("CollegeId");

                    b.HasIndex("CompanyId");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("summer_training_app.Models.TrainingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("TrainingRecords");
                });

            modelBuilder.Entity("summer_training_app.Models.TrainingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcadimicYear")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AcceptanceLetterPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationInWeeks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedCompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("TrainingRequests");
                });

            modelBuilder.Entity("summer_training_app.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6263),
                            IsActive = true,
                            LastUpdatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6265),
                            Name = "مدير",
                            PasswordHash = "$2a$11$wsY6aRAHZfIenc7om01jZuuRlHZ.fNguE9lCbPrkGUs2C0uXqM7hu",
                            PublicId = new Guid("353f8f8c-87f7-4baa-8f4e-42af7e9a5164"),
                            RoleId = 4,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6300),
                            IsActive = true,
                            LastUpdatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6303),
                            Name = "م. فهد (مشرف شركة)",
                            PasswordHash = "$2a$11$Hh2FjbRzwcQc7vbo57ewae7nG9ltg89LCtxJUbpMU6P/dTgqOLxUe",
                            PublicId = new Guid("898cef11-cad7-4948-930b-ac938d8e9373"),
                            RoleId = 2,
                            Username = "com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6316),
                            IsActive = true,
                            LastUpdatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6318),
                            Name = "د. خالد (مشرف كلية)",
                            PasswordHash = "$2a$11$OvswobrsWbDtYwwHwLzDOuwtuTUmdNxQXZdh0ANvO1yj/okeIA8/i",
                            PublicId = new Guid("c791234e-ec78-42cb-9a77-f87e817a0f2c"),
                            RoleId = 3,
                            Username = "col"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6330),
                            IsActive = true,
                            LastUpdatedAt = new DateTime(2026, 8, 5, 15, 10, 22, 299, DateTimeKind.Local).AddTicks(6332),
                            Name = "أحمد (طالب)",
                            PasswordHash = "$2a$11$A3yR1hLXMFnkrR3RFK/ZluLdRE0j22y140s6sgkcLuoAUPWb7PrEO",
                            PublicId = new Guid("6323615a-e662-480a-9bf5-dbfb158e3211"),
                            RoleId = 1,
                            Username = "stu"
                        });
                });

            modelBuilder.Entity("summer_training_app.Models.CollegeDocument", b =>
                {
                    b.HasOne("summer_training_app.Models.College", "College")
                        .WithMany("Documents")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");
                });

            modelBuilder.Entity("summer_training_app.Models.CollegeRepresentative", b =>
                {
                    b.HasOne("summer_training_app.Models.College", "College")
                        .WithMany("CollegeRepresentatives")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.User", "User")
                        .WithOne("CollegeRepresentative")
                        .HasForeignKey("summer_training_app.Models.CollegeRepresentative", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("User");
                });

            modelBuilder.Entity("summer_training_app.Models.Company", b =>
                {
                    b.HasOne("summer_training_app.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("summer_training_app.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("summer_training_app.Models.CompanyRepresentative", b =>
                {
                    b.HasOne("summer_training_app.Models.Company", "Company")
                        .WithMany("CompanyRepresentatives")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.User", "User")
                        .WithOne("CompanyRepresentative")
                        .HasForeignKey("summer_training_app.Models.CompanyRepresentative", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportAnswer", b =>
                {
                    b.HasOne("summer_training_app.Models.Reports.ReportQuestion", "ReportQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.Reports.StudentReport", "StudentReport")
                        .WithMany("Answers")
                        .HasForeignKey("StudentReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportQuestion");

                    b.Navigation("StudentReport");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportEvaluation", b =>
                {
                    b.HasOne("summer_training_app.Models.CompanyRepresentative", "CompanySupervisor")
                        .WithMany("Evaluations")
                        .HasForeignKey("CompanySupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.Reports.StudentReport", "StudentReport")
                        .WithMany("Evaluations")
                        .HasForeignKey("StudentReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanySupervisor");

                    b.Navigation("StudentReport");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportQuestion", b =>
                {
                    b.HasOne("summer_training_app.Models.Reports.ReportTemplate", "ReportTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportTemplate");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportTemplate", b =>
                {
                    b.HasOne("summer_training_app.Models.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.CollegeRepresentative", "CreatedByUser")
                        .WithMany("CreatedReportTemplates")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.StudentReport", b =>
                {
                    b.HasOne("summer_training_app.Models.StudentProfile", "StudentProfile")
                        .WithMany("StudentReports")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.Reports.ReportTemplate", "ReportTemplate")
                        .WithMany("StudentReports")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.TrainingRecord", "TrainingRecord")
                        .WithMany("StudentReports")
                        .HasForeignKey("TrainingRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportTemplate");

                    b.Navigation("StudentProfile");

                    b.Navigation("TrainingRecord");
                });

            modelBuilder.Entity("summer_training_app.Models.RoleUpgradeRequest", b =>
                {
                    b.HasOne("summer_training_app.Models.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeId");

                    b.HasOne("summer_training_app.Models.Role", "RequestedRole")
                        .WithMany()
                        .HasForeignKey("RequestedRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.User", "User")
                        .WithMany("RoleUpgradeRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("RequestedRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("summer_training_app.Models.StudentProfile", b =>
                {
                    b.HasOne("summer_training_app.Models.College", "College")
                        .WithMany("StudentProfiles")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("summer_training_app.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("summer_training_app.Models.TrainingRecord", b =>
                {
                    b.HasOne("summer_training_app.Models.Company", "Company")
                        .WithMany("TrainingRecords")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("summer_training_app.Models.StudentProfile", "Student")
                        .WithMany("TrainingRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("summer_training_app.Models.TrainingRequest", b =>
                {
                    b.HasOne("summer_training_app.Models.Company", "Company")
                        .WithMany("TrainingRequests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("summer_training_app.Models.StudentProfile", "Student")
                        .WithMany("TrainingRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("summer_training_app.Models.User", b =>
                {
                    b.HasOne("summer_training_app.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("summer_training_app.Models.College", b =>
                {
                    b.Navigation("CollegeRepresentatives");

                    b.Navigation("Documents");

                    b.Navigation("StudentProfiles");
                });

            modelBuilder.Entity("summer_training_app.Models.CollegeRepresentative", b =>
                {
                    b.Navigation("CreatedReportTemplates");
                });

            modelBuilder.Entity("summer_training_app.Models.Company", b =>
                {
                    b.Navigation("CompanyRepresentatives");

                    b.Navigation("TrainingRecords");

                    b.Navigation("TrainingRequests");
                });

            modelBuilder.Entity("summer_training_app.Models.CompanyRepresentative", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.ReportTemplate", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("StudentReports");
                });

            modelBuilder.Entity("summer_training_app.Models.Reports.StudentReport", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("summer_training_app.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("summer_training_app.Models.StudentProfile", b =>
                {
                    b.Navigation("StudentReports");

                    b.Navigation("TrainingRecords");

                    b.Navigation("TrainingRequests");
                });

            modelBuilder.Entity("summer_training_app.Models.TrainingRecord", b =>
                {
                    b.Navigation("StudentReports");
                });

            modelBuilder.Entity("summer_training_app.Models.User", b =>
                {
                    b.Navigation("CollegeRepresentative")
                        .IsRequired();

                    b.Navigation("CompanyRepresentative")
                        .IsRequired();

                    b.Navigation("RoleUpgradeRequests");

                    b.Navigation("StudentProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
